"""Add message

Revision ID: bf566ebff1ce
Revises: 9f3c7bc86e22
Create Date: 2017-04-10 21:55:19.646412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf566ebff1ce'
down_revision = '9f3c7bc86e22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=64), nullable=True),
    sa.Column('nick', sa.String(length=64), nullable=True),
    sa.Column('messages', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_channel'), 'messages', ['channel'], unique=False)
    op.create_index(op.f('ix_messages_nick'), 'messages', ['nick'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_nick'), table_name='messages')
    op.drop_index(op.f('ix_messages_channel'), table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
